services:
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - SERVER_PORT=8080
    ports:
      - 19091:8080

  prometheus:
    #docker run --name prometheus -d -p 9090:9090 prom/prometheus
    image: 'prom/prometheus'
    ports:
      - 19090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  demo-kafka-consumer:
    image: 'localhost:5000/mariusdw.com/demo-kafka-consumer:latest'
    ports:
      - 18081:8081
    hostname: consumer
    entrypoint: java -jar -Dspring.profiles.active=dev /opt/app.jar

  demo-kafka-producer:
    image: 'localhost:5000/mariusdw.com/demo-kafka-producer:latest'
    ports:
      - 18080:8080
    hostname: producer
    entrypoint: java -jar -Dspring.profiles.active=dev /opt/app.jar